### PR TITLE
fix: add Node.js v24 to AWS Lambda supported runtimes (#578)

### LINKED ISSUE #578: nodejs24.x not supported
**Describe the bug**
I want to deploy on newly available Lambda runtime nodejs24.x 

Deployment fails on nodejs24.x

**To Reproduce**
Steps to reproduce the behavior. If you have an example repository that would be even better:

1. Change your serveless configuration to nodejs24.x
2. Run `sls deploy`

**Expected behavior**
Should deploy on node 24

**Screenshots or Logs**

 at new AssertionError (node:internal/assert/assertion_error:376:5)
x:deploy-db:     at assertIsSupportedRuntime (/Users/slegault/project/bitbucket/x/node_modules/serverless-esbuild/dist/helper.js:253:15)
x:deploy-db:     at EsbuildServerlessPlugin.getBuildOptions (/Users/slegault/project/bitbucket/x/node_modules/serverless-esbuild/dist/index.js:249:47)

**Versions (please complete the following information):**

    "esbuild": "^0.27.0",
    "serverless-esbuild": "^1.56.0",

**Additional context**
The following values should be updated

export type AwsNodeMatcher = AwsNodeProviderRuntimeMatcher<12 | 14 | 16 | 18 | 20 | 22>;

const awsNodeMatcher: AwsNodeMatcher = {
  'nodejs22.x': 'node22',
  'nodejs20.x': 'node20',
  'nodejs18.x': 'node18',
  'nodejs16.x': 'node16',
  'nodejs14.x': 'node14',
  'nodejs12.x': 'node12',
};

### PR DESCRIPTION
**Pull request by tiagocpeixoto**
Fixes #578

### CODE REVIEW

**Review by floydspace — APPROVED** [review]

File: src/helper.ts [hunk 1]
```diff
@@ -231,7 +231,7 @@ export type ScalewayNodeProviderRuntimeMatcher<Versions extends number> = {
   [Version in Versions as `node${Version}`]: `node${Version}`;
 };
 
-export type AwsNodeMatcher = AwsNodeProviderRuntimeMatcher<12 | 14 | 16 | 18 | 20 | 22>;
+export type AwsNodeMatcher = AwsNodeProviderRuntimeMatcher<12 | 14 | 16 | 18 | 20 | 22 | 24>;
```
Comment (crespowang) [inline src/helper.ts:234]: can probably remove the versions before 20 as they are no longer supported by AWS Lambda nodejs runtime.
